package com.awab.calculator.view

const val THEME_SHARED_PREFERENCES = "THEME_SHARED_PREFERENCES"
const val CURRENT_THEME = "CURRENT_THEME"
const val CURRENT_DARK_MODE_STATE = "CURRENT_DARK_MODE_STATE"
const val SETTINGS_REQUEST_CODE = 999
const val SETTINGS_CHANGED_EXTRA = "SETTINGS_CHANGED_EXTRA"